#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     color,          sensorCOLORFULL)
#pragma config(Sensor, S3,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     block,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     tail,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     slide,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"



task baseDrive()
{
	int leftWheelPower, rightWheelPower;
	while(true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y2)<10)								// this deals with joystick "noise"
			leftWheelPower = 0;
		else
			leftWheelPower = joystick.joy1_y2/14.1;

		if(abs(joystick.joy1_y1)<10)
			rightWheelPower = 0;
		else
			rightWheelPower = joystick.joy1_y1/14.1  ;

		leftWheelPower *= leftWheelPower*sgn(leftWheelPower);			//square it...
		rightWheelPower *= rightWheelPower*sgn(rightWheelPower);

		motor[leftWheel] = leftWheelPower;
		motor[rightWheel] = rightWheelPower;

		if (joy1Btn(1) == 1)									// start tail command
			motor[tail] = 100;

		if (joy1Btn(2) == 1)									// stop tail
			motor[tail] = 0;

		if (joy1Btn(3) == 1)
			motor[tail] = -100;

	}
}

task slideDrive()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(joystick.joy2_TopHat == 0)
		{
			motor[slide] = 100; //REMEMBER TO CHANGE
		}
		else if(joystick.joy2_TopHat == 4 )
		{
			motor[slide] = -100;
		}
		else
		{
			motor[slide] = 0;
		}


	}
}

task catrinDrive() //FOR CATRIN TO DRIVE
{
	while(true)
	{
		getJoystickSettings(joystick);

		if(joy2Btn(1))
		{
			motor[block] = 100;
		}
		if(joy2Btn(8))
		{
			motor[block] = -0;
		}
		if(joy2Btn(2))
		{
			motor[block] = -100;
		}

	}
}

task dylanDrive() //FOR DYLAN TO DRIVE
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy2Btn(8))
		{
			motor[block] = -100;
		}
		if(joy2Btn(6))
		{
			motor[block] = 100;
		}
		if(joy2Btn(7))
		{
			motor[block] = 0;
		}
	}
}

void waitForSelection ()
{
	getJoystickSettings(joystick);
	while (joy2Btn(9) == 0 && joy2Btn(10) == 0) //Waiting for a program to be chosen.
		getJoystickSettings(joystick);
}

void startSelection ()
{
	if (joy2Btn(9) == 1)
	{
		StartTask (catrinDrive);
		StopTask (dylanDrive);
	}
	if (joy2Btn(10) == 1)
	{
		StartTask (dylanDrive);
		StopTask (catrinDrive);
	}
}

//task armDrive()
//{
//	while (true)
//	{
//		getJoystickSettings(joystick);
//		if(joy2Btn(11)==1)
//		{
//			motor[arm] = 20;
//		}
//		else if (joy2Btn(12)==1)
//		{
//			motor[arm] = -20;
//		}
//		else
//		{
//			motor[arm] = 0;
//		}
//	}
//}
task main()
{
	bFloatDuringInactiveMotorPWM = false; //remove later
	StartTask (baseDrive);
	StartTask (slideDrive);
	//StartTask (armDrive);
	StartTask (dylanDrive);

	waitForSelection ();

	startSelection();

	while(true) //just in case the driver wants to switch in between them or presses the wrong button.
	{
    waitForSelection();
    startSelection();
	}

}
