#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    topLeft,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    bottomLeft,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    tail,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_1,    topRight,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bottomRight,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void home()
{
	servo[bottomLeft] = 64-6;
	servo[bottomRight] = 64+6;

	servo[topLeft] = 64-11;
	servo[topRight] =64+11;
}


void drop(){
		servo[bottomLeft] = 64-5;
	servo[bottomRight] = 64+5;
	servo[topLeft] = 64-5;
	servo[topRight] = 64+5 ;
}

void pick(){
	servo[bottomLeft] = 64-3;
	servo[bottomRight] = 64+3;
	servo[topLeft] = 64-8;
	servo[topRight] = 64+8 ;
}

void inter(){
	  servo[bottomLeft] = 64-10;
	servo[bottomRight] = 64+10;
	servo[topLeft] = 64-8;
	servo[topRight] = 64+8;
}


task main()
{
	while(true){

bFloatDuringInactiveMotorPWM = false;

//	servo[bottomLeft] = 65;
//	servo[bottomRight] = 63;
//	servo[topRight] = 64;
//	servo[topLeft] = 64;
//	wait1Msec(5000);
//	servo[bottomLeft] = 64;
//	servo[bottomRight] = 64;
//	servo[topRight] = 63;
//	servo[topLeft] = 65;
//	wait1Msec(5000);
//	servo[bottomLeft] = 63;
//	servo[bottomRight] = 65;
//	wait1Msec(5000);

home();
wait1Msec(5000);



	pick();
	wait1Msec(5000);

		inter();
	wait1Msec(5000);

	drop();
	wait1Msec(5000);



}
//servo[topRight] = 64;
//servo[topLeft] = 64;

}
