#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     distance,       sensorSONAR)
#pragma config(Sensor, S3,     rightIR,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     leftIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          midMotor,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

 task main()
{
	int sensor1;
	int sensor2;
	while(true){
			sensor1 = SensorValue[leftIR];
			sensor2 = SensorValue[rightIR];
			nxtDisplayCenteredTextLine(3, "%d, %d", sensor1, sensor2);
				//if beacon is not in sight
				if(SensorValue(leftIR)==0 && SensorValue(rightIR)==0){
					motor[leftMotor] = 0;
					motor[rightMotor] = 100;
				}
				//if beacon is on the left
				if(SensorValue(leftIR)<=5 && SensorValue(leftIR)>0 && SensorValue(rightIR)<=5 && SensorValue(rightIR)>0){
						//turn left
						motor[leftMotor] = 40;
						motor[rightMotor] = 80;
				}
				//if beacon is on the right
				if(SensorValue(leftIR)>5 && SensorValue(rightIR)>5){
						//turn right
						motor[leftMotor] = 80;
						motor[rightMotor] = 40;
				}
				//if beacon is straight ahead
				if(SensorValue(leftIR)>5 && SensorValue(rightIR)<5){
						//stay on course
						motor[leftMotor] = 80;
						motor[rightMotor] = 80;
				}
				//if beacon is right in front
				if(SensorValue(leftIR)==7 && SensorValue(rightIR)==3){
						//stop
						motor[leftMotor] = 0;
						motor[rightMotor] = 0;
				}
				if(SensorValue[distance] < 15){
					motor[leftMotor] = -100;
					motor[rightMotor] = -100;
					wait1Msec(1500);
				}
				}
			}
