#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_1,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Servo Control by NXT Motor -                                      *|
|*                                        ROBOTC on NXT + TETRIX                                          *|
|*                                                                                                        *|
|*  This program simply sweeps the servo back and forth.  Servo Change Rate can be changed by changing    *|
|*  'delta'.  (0 = max servo speed, # > 0 = how many servo positions to move per update (every 20ms).     *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  Be sure to attach a servo somewhere on the robot.                                               *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 1                  none                TETRIX Controller   TETRIX                              *|
|*    Port 1 - Chan. 1        servo1              std. Servo          The servo that you wish to test.    *|
\*---------------------------------------------------------------------------------------------------4246-*/
task main()
{
  int delta = 1;                        // Create int 'delta' to the be Servo Change Rate.
	int dd = -3;
	int base = 64;

  while(true)
  {
    //servoChangeRate[servo1] = delta;          // Slow the Servo Change Rate down to only 'delta' positions per update.

    //if(ServoValue[servo1] < 32)              // If servo1 is closer to 0 (than 255):
    //{
    //  while(ServoValue[servo1] < 32)               // While the ServoValue of servo1 is less than 255:
    //  {
    //    servo[servo1] = 32;                              // Move servo1 to position to 255.
    //  }
    //}

    //wait1Msec(1000);                          // Wait 1 second.

    //if(ServoValue[servo1] >= 32)             // If servo1 is closer to 255 (than 0):
    //{
    //  while(ServoValue[servo1] > 0)                 // While the ServoValue of servo1 is greater than 0:
    //  {
    //    servo[servo1] = 0;                                // Move servo1 to position to 0.
    //  }
    //}


    servo[servo1] = base;
  	servo[servo2] = base;
  	servo[servo7] = base;
  	servo[servo8] = base;

  	//servo[servo6]=0;\vo7] = base;

    servo[servo2] = base;
    servo[servo8] = base;

    nxtDisplayString(1,"%d",ServoValue[servo1]);
    nxtDisplayString(2,"%d",ServoValue[servo2]);


    wait1Msec(1000);
    dd = dd+1;
  }
}
