#pragma config(Sensor, S1,     gate1,          sensorSONAR)
#pragma config(Sensor, S2,     gate2,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int measure() {

	if(SensorValue[gate1]<40) {
		ClearTimer(T1);
		nxtDisplayClearTextLine(4);
		PlayTone(1000, 250);
		while(SensorValue[gate2]>30){
			nxtDisplayCenteredTextLine(4, "%s", time1[T1]);
    }
	}
		PlayTone(1200, 250);
    int finalTime = time1[T1];
    return finalTime;
}


task main()
{

measure();
nxtDisplayClearTextLine(3);
nxtDisplayCenteredTextLine(4, "%s, %s", time1[T1]);

}
