#pragma config(Sensor, S1,     backTouch,      sensorTouch)
#pragma config(Sensor, S2,     rightIR,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     leftIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     colourSensor,   sensorCOLORFULL)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
		{
			int sensor4 = SensorValue[colourSensor];
			nxtDisplayCenteredTextLine(3, "%d, %d", sensor4);
			if(SensorValue(colourSensor)==2){
					motor[leftMotor] = 50;
					motor[rightMotor] = 100;

				}
				else {
					motor[leftMotor] = 100;
					motor[rightMotor] = 50;


				}
//wait1Msec(3000);
}

}
