#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     controller,     sensorI2CMuxController)
#pragma config(Sensor, S2,     color,          sensorCOLORFULL)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"  // just files to make the SMUX work.
#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"               // the files for the Logitech controller to work by USB to the laptop and then by bluetooth/USB to the NXT, NOT by samantha module.

#define DEBUG														// used only for debugging... delete when trying the program for real.

const tMUXSensor irLeft = msensor_S4_1; // configuring the IR sensor over the SMUX.
const tMUXSensor irRight = msensor_S4_2;







void seekBeacon(){														// function for finding the IR beacon, called seekBeacon.

	int valRight;
	int valLeft;

	while(true){

			valRight = HTIRS2readDCDir(irRight);
			valLeft  = HTIRS2readDCDir(irLeft);

#ifdef DEBUG
			nxtDisplayCenteredTextLine(3, "%d, %d", valLeft, valRight);
#endif

				//if beacon is not in sight
				if(valLeft==0 && valRight==0){
					motor[leftMotor] = -75;
					motor[rightMotor] = 75;
					break;
				}

				//if beacon is on the left
				if(valLeft<=5 && valLeft>0 && valRight<=5 && valRight>0){
						//turn left
						motor[leftMotor] = 0;
						motor[rightMotor] = 100;
						break;
				}
				//if beacon is on the right
				if(valLeft>5 && valRight>5){
						//turn right
						motor[leftMotor] = 100;
						motor[rightMotor] = 0;
						break;
				}
				//if beacon is straight ahead
				if(valLeft>5 && valRight<5){
						//stay on course
						motor[leftMotor] = 80;
						motor[rightMotor] = 80;
						break;
				}
				//if beacon is right in front
				if(valLeft==7 && valRight==3){
						//stop
						motor[leftMotor] = 0;
						motor[rightMotor] = 0;
						break;
				}


				}
}



void dropBlock() {		// called after seekBeackon to drop the block...

}

void driver() {					// the driver controlled program, which is also for the endgame.
	int leftStick = joystick.joy1_y1;    // giving easier names to the two joysticks that are used for the wheels.
	int rightStick = joystick.joy1_y1;

	while(true) {
		getJoystickSettings(joystick);  // updating the joystick controller and the buttons.
		motor[leftMotor] = leftStick;
		motor[rightMotor] = rightStick;
	}

}

  task main()
{
	seekBeacon(); // calling the function from above.
	dropBlock();

}
