#pragma config(Sensor, S1,     leftIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     rightIR,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     colourSensor,   sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          tailServo,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*“Coding Hamburger”
At the top you have your pragma statement and import statements
In the middle, you have your meaty main method
At the bottom, you have random methods and closing statements./*

Basic Framework: */
#include "JoystickDriver.c";

bool beaconmode = true;
bool rampmode = false;
bool gotoramp = false;
bool onramp = false;
bool tailspinner = false;
int tailspinnervalue = 56;

task main ()
{
	waitForStart();
	while(true)
	{
		if(/*INSERT SAMANTHA MODULE GIBBERISH HERE*/){
			if(beaconmode==true){
				//if beacon is on the left
				if(SensorValue(leftIR)<5 && SensorValue(rightIR)<5){
						//turn left
						motor[leftMotor] = 60;
						motor[rightMotor] = 80;
				}
				//if beacon is on the right
				if(SensorValue(leftIR)>5 && SensorValue(rightIR)>5){
						//turn right
						motor[leftMotor] = 80;
						motor[rightMotor] = 60;
				}
				//if beacon is straight ahead
				if(SensorValue(leftIR)>5 && SensorValue(rightIR)<5){
						//stay on course
						motor[leftMotor] = 80;
						motor[rightMotor] = 80;
				}
				//if beacon is right in front
				if(SensorValue(leftIR)==7 && SensorValue(rightIR)==3){
						//stop
						motor[leftMotor] = 0;
						motor[rightMotor] = 0;
				}
				if(/* block is dropped in basket */){
					//INSERT CODE HERE
					beaconmode = false;
					gotoramp = true;
				}
			}
			if(gotoramp==true){
				//GET FROM RAMP TO LINE
				gotoramp=false;
				rampmode=true;
			}
			if(rampmode==true){
				if(SensorValue(colourSensor)==17){
					motor[leftMotor] = 60;
					motor[rightMotor] = 80;
				}
				if(/*robot on ramp */){
					motor[leftMotor] = 0;
					motor[rightMotor] = 0;
				}
				else {
					motor[leftMotor] = 80;
					motor[rightMotor] = 60;
				}
			}
		if(/* MORE SAMANTHA MODULE GIBBERISH HERE */){
			if(true){
				getJoystickSettings(joystick);
				motor[leftMotor] = joystick.joy1_y1;
	   		motor[rightMotor] = joystick.joy1_y2;
	 		}
	    if(tailspinner==true){
	    	servo[tailServo] = tailspinnervalue;
	    	if(/*button is pressed on controller */){
	    		//spin one way
	    		tailspinnervalue = tailspinnervalue+1;
	    		servo[tailServo] = tailspinnervalue;
				}
				if(/*other button is pressed on controller */){
					tailspinnervalue = tailspinnervalue-1;
					servo[tailServo] = tailspinnervalue;
	 			}
	 		}
	  }
	}
}
