#pragma config(Hubs,  S1, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_1,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo12,              tServoStandard)
#pragma config(SrvoPosition,  Position01,            128, 128, 128, 128, 128, 128, 128, 128)
#pragma config(SrvoPosition,  Position02,            128, 128, 128, 128, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  bSystemLeaveServosEnabledOnProgramStop = false;

  int delta = 1;                        // Create int 'delta' to the be Servo Change Rate.
  int step = 0;
  int p0;

  p0 = ServoValue[servo6];

  //servo[servo6] = 128;

  while(true)
  {
  	nxtDisplayCenteredTextLine(3, "%d %d", 1, ServoValue[servo1]);
    nxtDisplayCenteredTextLine(4, "%d %d", 6, ServoValue[servo6]);



  }
}
