#pragma config(Motor,  motorA,          rMotor,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          lMotor,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
{

motor[rMotor] = 75;
motor[lMotor] = 75;
wait1Msec(500);
motor[rMotor] = -75;
motor[lMotor] = -75;


/* while(SensorValue[sonar] >=20)
	{
		motor[motorA] = 75;
		motor[motorC] = 75;

}
while (SensorValue[sonar] < 20)
{
	motor[motorA] = -75;
	motor[motorC] = -75;
	wait1Msec(1000);
}
*/
}

}
