#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{
	while(true)
	{
		//90 degrees: 50 and 59
/*	servoTarget[servo1] = 100;
	wait1Msec(5000);
	servoTarget[servo1] = 109;
	wait1Msec(5000);
*/
//not vaccum gate: 45, 160
	servoTarget[servo2] = 45;
	wait1Msec(1000);
	servoTarget[servo2] = 160;
	wait1Msec(1000);

	/*
	servoTarget[servo1] = 100;
	wait1Msec(5000);
	servo[servo1] = 110;
	wait1Msec(1000);
	*/
	}

}
