#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     color,          sensorCOLORFULL)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     tail,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     slide,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     block,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"	// just files to make the SMUX work.
#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"

const tMUXSensor irLeft = msensor_S4_1;		// configuring the IR sensor over the SMUX.
const tMUXSensor irRight = msensor_S4_4;

int compassVal;
void findBeacon()
{
	while(HTIRS2readACDir(irLeft) != 5 || HTIRS2readACDir(irRight) !=5)
	{
		motor[leftWheel] = 30;
		motor[rightWheel] = 30;
}
}
task main()
{

	waitForStart();


}
