#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     controller,     sensorNone)
#pragma config(Sensor, S2,     color,          sensorCOLORFULL)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  motorA,          collectMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     backSlide,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     tailMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    topLeft,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    bottomLeft,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_1,    topRight,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bottomRight,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"	// just files to make the SMUX work.
#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"



task baseDrive()
{
	int leftWheelPower, rightWheelPower;
	while(true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y2)<10)								// this deals with joystick "noise"
			leftWheelPower = 0;
		else
			leftWheelPower = joystick.joy1_y2/12.8;

		if(abs(joystick.joy1_y1)<10)
			rightWheelPower = 0;
		else
			rightWheelPower = joystick.joy1_y1/12.8;

		leftWheelPower *= leftWheelPower*sgn(leftWheelPower);			//square it...
		rightWheelPower *= rightWheelPower*sgn(rightWheelPower);

		motor[leftWheel] = leftWheelPower;
		motor[rightWheel] = rightWheelPower;

		if (joy1Btn(1) == 1)									// start tail command
			motor[tailMotor] = 255;  // or 255

		if (joy1Btn(2) == 1)									// stop tail
			motor[tailMotor] = 127;

		if (joy1Btn(3) == 1)
			motor[tailMotor] = 0;

	}
}

task slideDrive()
{

	while(true)
	{
		int slidePower, collectPower;
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y2)<10)								// this deals with joystick "noise"
			slidePower = 0;
		else
			slidePower = joystick.joy1_y2/12.8;

		if(abs(joystick.joy1_y1)<10)
			collectPower = 0;
		else
			collectPower = joystick.joy1_y1/12.8;

		slidePower *= slidePower*sgn(slidePower);			//square it...
		collectPower *= collectPower*sgn(collectPower);

		motor[backSlide] = slidePower;
		motor[collectMotor] = collectPower;
	}
}

task main()
{
	wait10Msec(100);
	StartTask (baseDrive);	// start the baseDrive task
	StartTask (slideDrive);		// start the armDrive
	while(true)							// main thread does nothing but wait...
		wait10Msec(50);

}
